# -*- coding: utf-8 -*-
"""Hola.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jz_kzif7gOAczpSj9eOjh1xHDdDG0tJV
"""

import this